### ISSUE TITLE
LightCurveCollection.Stitch() LightkurveWarning and astropy.utils.metadata.MergeConflictError

### ISSUE THREAD

**Issue by JonahDG** [lightkurve/lightkurve#1148]
#### Problem description
When running LightCurveCollection.Stitch() I am running into a LighkurveWarning that excludes columns from stitching because of incompatible data types (this is probably intended), but I am also getting  'astropy.utils.metadata.MergeConflictError: Arrays have incompatible types ['int32', 'int32', 'int32', 'int32', 'str32', 'int32', 'int32', 'int32', 'int32', 'int32', 'int32', 'str32', 'int32', 'int32', 'str32', 'int32', 'int32', 'int32', 'str32', 'int32', 'int32', 'int32', 'str32', 'int32', 'int32', 'int32', 'str32', 'int32', 'int32', 'int32', 'str32', 'int32', 'int32', 'int32', 'str32', 'int32', 'int32', 'int32', 'str32', 'int32', 'int32', 'int32', 'str32', 'int32', 'int32', 'int32', 'str32', 'int32', 'int32', 'str32'].

#### Example

```python
import lightkurve as lk
TIC='TIC 30031439'
lcCollection=lk.search_lightcurve(TIC, mission="TESS").download_all()
lcStitched=lcCollection.stitch()
```

#### Expected behavior
I would expect 'lcStitched' to be a stitched light curve. This worked with the pre-2.0 version of this code in LightKurve.

#### Environment

-  platform (e.g. Linux, OSX, Windows): OSX Big Sur 11.6
-  lightkurve version (e.g. 1.0b6): 2.0.11
-  installation method (e.g. pip, conda, source): pip

**Comment by JonahDG** [comment]
I am still having this issue, can I get any suggestions on how to proceed?

**Comment by JonahDG** [comment]
Is there any updates on this issue? I can answer questions about the errors messages that I am getting, but a response would be appreciated.

**Comment by barentsen** [comment]
@JonahDG Thank you for reporting this issue!  I'll investigate this as soon as time allows.

**Comment by ZRupp** [comment]
Any update on this? We're having to ignore a lot of data because of this issue.

**Comment by JonahDG** [comment]
I haven't figured out a solid work around other than tossing a Try and Except in

**Comment by JonahDG** [comment]
I haven't found a work around other than just tossing a try and except in the code

**Comment by ZRupp** [comment]
That's what I've been doing as well. I'll let you know if I find a better solution.

**Comment by christinahedges** [comment]
I believe the problem here is that this line:
```python
lcCollection=lk.search_lightcurve(TIC, mission="TESS").download_all()
```

Is downloading light curves from many different authors and so they don't stitch well together. To avoid this problem, you should a) specify which author you want TESS light curves from (e.g. `'SPOC'` products are the mission light curves, `'QLP'` products are produced by MIT etc) and b) generally not stitch together light curves from different authors.

I will note that there seems to be a bug that `'CDIPS'` author light curves can not be stitched which seems to be a bug, I'm going to open an issue, and please note that `'TGLC'` author light curves are new, and so you will need `Lightkurve` v2.4.1+ to be able to read those in (see #1286).
